name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change Permission
        run: chmod +x ./gradlew

      - name: Execute Gradle check
        run: ./gradlew ktlintCheck